### ISSUE TITLE
example argument for iri_baker?

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/iribaker#1]
Hi, I've installed iribaker according the instructions and am following up on the example from the readme file, but am unable to attain the suggested output.

```
import iribaker
iribaker.to_iri(string)
```

Results in: 

> > NameError: name 'string' is not defined

Quoting the string doesn't help:

```
import iribaker
iribaker.to_iri("string")
```

> > The argument you provided does not comply with RFC 3987 and is not parseable as a IRI
> > ERROR:iribaker:The argument you provided does not comply with RFC 3987 and is not parseable as a IRI
> > string
> > ERROR:iribaker:string
> > ERROR: An unexpected error occurred while tokenizing input
> > The following traceback may be corrupted or invalid
> > The error message is: ('EOF in multi-line string', (1, 66))

Could you please provide another example?

**Comment by RinkeHoekstra** [comment]
Well.... iribaker expects an IRI-like string. If it is _almost_ an IRI, it will try to fix it. If it is too far off, it will throw errors (as in your case)
